[package]
name = "pentest"
description = "A zero dependency network penetration test tool."
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://pentest.wtf"
repository = "https://github.com/ca333/pentest"
readme = "README.md"

[dependencies]
